// DE38ECB3
// This code was generated by a tool.
// date: 03/05/2017 11:20:35

namespace Perpetuum.ExportedTypes
{

	public enum TechTreePointType 
	{
		undefined = 0,
 		common = 5,
		hitech = 6,
		industrial = 4,
		newtech = 7,
		nuimqol = 3,
		pelistal = 2,
		thelodica = 1
	}
}
