// 4998443E
// This code was generated by a tool.
// date: 03/05/2017 11:20:35

namespace Perpetuum.ExportedTypes
{

	public enum TechTreeGroup 
	{
 		common1 = 6,
		common2 = 9,
		indy = 8,
		nuimqol = 3,
		pbs = 7,
		pelistal = 4,
		thelodica = 5
	}
}
