// 322AC318
// This code was generated by a tool.
// date: 03/05/2017 11:20:35

namespace Perpetuum.ExportedTypes
{

	public enum TierType 
	{
		Undefined = 0,
 		Normal = 1,
		Prototype = 2,
		Special = 3
	}
}
